### ISSUE TITLE
Plainpad and Docker

### ISSUE THREAD

**Issue by Antoine2tt** [alextselegidis/plainpad#14]
Hello ! I'm very interested about Plainpad. 
But i prefer to use it with Docker. 

Is it planned for Plainpad to be usable with Docker ?

Thanks !

**Comment by alextselegidis** [comment]
Hello!

Sure, check out this guide: 

https://github.com/alextselegidis/plainpad/blob/master/docs/docker.md

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
