### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by ItsNoted** [alextselegidis/plainpad#33]
Any plans for a dark mode? ;)

**Comment by ItsNoted** [comment]
Found it already has one!

Maybe add a features list and put this in there?

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this. 

A new website will be put together to support Plainpad soon. 

All the features will be listed there. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
