### ISSUE TITLE
crypted notes

### ISSUE THREAD

**Issue by gwlegion** [alextselegidis/plainpad#45]
hi ... first, many thanks for your work ... it's a very good app !

can you plan to add crypted notes ? for password or other critical stuff storage ?

**Comment by alextselegidis** [comment]
Hello! 

There is already encryption supposed in the app (based on the Laravel app key value). 

You can enable this from the settings page of the user. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
