### ISSUE TITLE
Suggestion: Improve line wrapping in the notes list.

### ISSUE THREAD

**Issue by virtadpt** [alextselegidis/plainpad#5]
![plainpad_example](https://user-images.githubusercontent.com/639730/83933544-5ac75a00-a75e-11ea-8adb-04b77f0c0608.png)
In the "list of notes" sidebar of Plainpad, line wrapping seems to be a little... confused?  Uncertain?  When a fraction of a glyph hits the edge of the sidebar, Plainpad adds another line but doesn't actually word-wrap onto that new line.  It would make the UX nicer if it was less conservative about rewrapping text onto the new blank line.

**Comment by alextselegidis** [comment]
Hello @virtadpt 

You are right, this needs to be improved.

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
