### ISSUE TITLE
[Feature request] OIDC/OAuth/Single Sign-On

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [alextselegidis/plainpad#66]
First of all, thanks for your nice project. I am wondering if you could introduce single sign-on in this APP? I am using my own identity manager and sharing my stuff in my family. I believe many people who are doing self-hosting are expecting this feature.

**Comment by alextselegidis** [comment]
Hello! 

Yes, integrating LDAP is on my roadmap for a future release. 

Cannot tell yet how long this will take though. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
