### ISSUE TITLE
demo down

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [alextselegidis/plainpad#67]
Cannot login with the credentials provided.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reporting this, let me check. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
FYI Fixed

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Plainpad Creator <br><a href="https://alextselegidis.com">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
