### ISSUE TITLE
Please make it possible to configure login session timeouts.

### ISSUE THREAD

**Issue by virtadpt** [alextselegidis/plainpad#7]
What happens: User is typing away in a note, and then the Plainpad login session times out, bouncing the user back to the login screen.  Sometimes what was typed has been saved, sometimes not.

What would be helpful: Add an option to the admin Settings panel to configure the timeout.

**Comment by alextselegidis** [comment]
Hello @virtadpt 

This seems to be a good thing to configure. 

I will do this in a future release. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by RoiArthurB** [comment]
Hello,

I'd really love to have this feature too. Either configuring the timeout or simply being able to dis/enable the timeout feature per instance.

**Comment by alextselegidis** [comment]
Hello!

That will be a good one, but I'll mark this for v1.1.0 as there's a feature lock for the final v1.0.0, which will only include bug fixes. 

For now you could change the code in the `SessionsController.php` and set the expiration time to your preferred value:

https://github.com/alextselegidis/plainpad/blob/master/server/app/Http/Controllers/V1/SessionsController.php#L52

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Good news, this will be in place for the final 1.0.0, which will be released within December! 

I went for an optional configuration entry, where you will be able to add a `SESSION_LIFETIME=###` (in minutes) in the root .env file to change the default timeout (which is currently 12 hours). 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
