### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Ygarr** [alextselegidis/plainpad#78]
"unknown shorthand flag: 'd' in -d"
and/or
"docker: 'compose' is not a docker command."

**Comment by alextselegidis** [comment]
Hello! 

Please make sure you have the latest docker version installed and that the composer plug in is available 

`docker compose up -d`

This command should boot the development environment. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
