### ISSUE TITLE
Need to publish nginx configuration for self hosting

### ISSUE THREAD

**Issue by cruisemaniac** [alextselegidis/plainpad#8]
The documentation has a few missing steps:

1. The nginx configuration to get the server running isnt available
2. The build step does not seem to be included in the documentation. This would make a self hosted setup from a git clone really useful.

**Comment by alextselegidis** [comment]
Hello @cruisemaniac 

The app mainly needs NGINX configuration that is compatible to the Laravel PHP framework. 

You can try following this tutorial: 

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-laravel-with-nginx-on-ubuntu-20-04

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
