### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by raystek** [alextselegidis/plainpad#80]
Hello,

I followed the quick setup instructions to clone the plainpad.git and got up and running with the docker compose. What is the URL to access plainpad?

I received "502 Bad Gateway" from nginx when trying http://host_ip.

The only working URL are http://host_ip:8025 (mailpit) and http://host_ip:8080 (phpmyadmin).

I am sure I am missing something. Please advise if anyone knows the answer. Thanks you.

**Comment by alextselegidis** [comment]
Hello! 

It should be the localhost:80 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
