### ISSUE TITLE
Can't log in after installing and seeding.

### ISSUE THREAD

**Issue by fcassata** [alextselegidis/plainpad#81]
As the subject states. Set this up in a fresh LXC Debian container on Proxmox. PHP 7.4. Did the seeding, can see the user in the DB, but get "Something went wrong while logging you in, please try again." in the front end when trying to log in with the default values. Can't see a relelvant error in logs, but probably just don't know where to look.

Would love to be able to spin this up to try it!

**Comment by alextselegidis** [comment]
Hello! 

Error messages and other useful info can be found in the storage/logs or server logs files. 

Feel free to open a new ticket with more information on what could have gone wrong. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
