### ISSUE TITLE
How do you provide the publicUrl if installing from github / releases ?

### ISSUE THREAD

**Issue by cruisemaniac** [alextselegidis/plainpad#9]
I downloaded the release from github and set it up on my server. When I try to login, the react frontend is trying to reach the laravel app at `https://sub.example.com/undefined/v1/sessions`.

I noticed that the code for this is from the `publicURL` variable which is filled in with `process.env.PUBLIC_URL`. In a pre-baked build, this doesnt exist. How do I fix this ?

**Comment by alextselegidis** [comment]
Hello @cruisemaniac 

Thanks for posting this! I already had another user experiencing the same problem and I therefore made some fixes on `master` to ensure that paths are relative when referencing the API. 

Can you try building the frontend from the `master` branch and see if you get the same error. 

FYI there will be a beta 4 release coming soon, featuring some additional fixes on the app. 

<small>
<table>
<tr>
<td><img src="https://cdn.alextselegidis.com/plainpad/logos/plainpad-online-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Plainpad Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
